# Generated by Django 5.1.7 on 2025-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='threatlog',
            name='ai_risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
