# Generated by Django 5.1.7 on 2025-04-16 15:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0002_alter_threatlog_options_threatlog_ai_risk_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Threat Log', 'verbose_name_plural': 'Threat Logs'},
        ),
        migrations.AddField(
            model_name='threatlog',
            name='affected_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='confidence_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='mitigation_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='packet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='protocol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='verification_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='ai_risk_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='threat_type',
            field=models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('ddos', 'DDoS'), ('brute_force', 'Brute Force'), ('exploit', 'Exploit'), ('data_exfiltration', 'Data Exfiltration'), ('unauthorized_access', 'Unauthorized Access'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddIndex(
            model_name='threatlog',
            index=models.Index(fields=['-timestamp'], name='threat_moni_timesta_61fe04_idx'),
        ),
        migrations.AddIndex(
            model_name='threatlog',
            index=models.Index(fields=['source_ip'], name='threat_moni_source__515dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='threatlog',
            index=models.Index(fields=['destination_ip'], name='threat_moni_destina_df6443_idx'),
        ),
        migrations.AddIndex(
            model_name='threatlog',
            index=models.Index(fields=['threat_type'], name='threat_moni_threat__e8989d_idx'),
        ),
        migrations.AddIndex(
            model_name='threatlog',
            index=models.Index(fields=['severity'], name='threat_moni_severit_8508cf_idx'),
        ),
    ]
