# Generated by Django 5.1.7 on 2025-04-16 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0003_alter_threatlog_options_threatlog_affected_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTrafficAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=500)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_requests', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('bot_traffic_percentage', models.FloatField(default=0.0)),
                ('suspicious_ips', models.JSONField(default=dict)),
                ('traffic_sources', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
    ]
