# Generated by Django 5.1.7 on 2025-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0004_websitetrafficanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetrafficanalysis',
            name='country_traffic',
            field=models.JSONField(default=dict),
        ),
    ]
