# Generated by Django 5.1.7 on 2025-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0005_websitetrafficanalysis_country_traffic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetrafficanalysis',
            name='country_traffic',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
