# Generated by Django 5.1.7 on 2025-04-17 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0006_alter_websitetrafficanalysis_country_traffic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatlog',
            old_name='affected_system',
            new_name='source_asn',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='mitigation_action',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='port',
        ),
        migrations.AddField(
            model_name='threatlog',
            name='destination_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='source_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='source_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='packet_count',
            field=models.IntegerField(default=1),
        ),
    ]
