# Generated by Django 5.1.7 on 2025-04-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0007_rename_affected_system_threatlog_source_asn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatlog',
            old_name='source_asn',
            new_name='affected_system',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='destination_port',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='source_port',
        ),
        migrations.AddField(
            model_name='threatlog',
            name='mitigation_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='packet_count',
            field=models.IntegerField(default=0),
        ),
    ]
