# Generated by Django 5.1.7 on 2025-04-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_monitoring', '0008_rename_source_asn_threatlog_affected_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlog',
            name='ai_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
    ]
