# Generated by Django 5.1.7 on 2025-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkwebalert',
            name='affected_data',
        ),
        migrations.RemoveField(
            model_name='darkwebalert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='darkwebalert',
            name='severity',
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='darkwebalert',
            name='title',
            field=models.CharField(default='Untitled Alert', max_length=255),
        ),
        migrations.AlterField(
            model_name='darkwebalert',
            name='source',
            field=models.CharField(default='Unknown Source', max_length=255),
        ),
    ]
